[package]
name = "rust-img"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25"
qrcode = "0.14"
base64 = "0.22"

[[bin]]
name = "gradient-img"

[[bin]]
name = "duplicate-img"

[[bin]]
name = "gen-qrcode"

[[bin]]
name = "image-base64"